builders:

  fakeBuilder:
    import: "package:fake_model/builder.dart"
    builder_factories: ["fakeBuilder"]
    build_extensions: {".dart": [".fake.g.dart"]}
    build_to: source
    auto_apply: root_package