name: fake_model
description: Automatically generate code for create fake model by annotating Dart classes.
repository: https://github.com/zyzdev/fake_model/tree/main/packages/fake_model
version: 0.0.6

environment:
  sdk: '>=2.19.3 <4.0.0'

topics:
  - data-model
  - build-runner
  - codegen

dependencies:
  meta: ^1.3.0
  analyzer: ^5.13.0
  build: ^2.0.0
  dart_style: ^2.3.1
  fake_model_annotation: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
