name: fake_model_annotation
description: Annotation for fake_model code generator only. More detail see [fake_model](https://pub.dev/packages/fake_model).
repository: https://github.com/zyzdev/fake_model/tree/main/packages/fake_model_annotation
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <4.0.0'

# Add regular dependencies here.
dependencies:
  meta: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
